#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/yb_bloom
#
# IDENTIFICATION
#    src/backend/access/yb_bloom/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/yb_bloom
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	yb_bloom.o \
	yb_bloom_stubs.o

include $(top_srcdir)/src/backend/common.mk
