#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/bloom
#
# IDENTIFICATION
#    src/backend/access/bloom/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/bloom
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	bloomam.o \
	bloom_page.o \
	bloom_stubs.o

include $(top_srcdir)/src/backend/common.mk
